# Generated by Django 6.1.2 on 2026-10-06 23:27

import django.db.models.deletion
import transporte.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('pasajero', 'Pasajero'), ('conductor', 'Conductor'), ('representante', 'Representante legal'), ('admin', 'Administrador')], default='pasajero', max_length=15)),
                ('rut', models.CharField(blank=True, help_text='Formato 12345678-5', max_length=12, null=True, unique=True)),
                ('foto', models.ImageField(blank=True, help_text='Foto para que los pasajeros identifiquen al conductor', upload_to=transporte.models.ruta_foto)),
                ('debe_cambiar_clave', models.BooleanField(default=False, help_text='Se le exigirá cambiar la contraseña al ingresar')),
                ('representante', models.ForeignKey(blank=True, help_text='Representante legal responsable de este conductor', limit_choices_to={'perfil__rol': 'representante'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conductores_a_cargo', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recorrido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('geometria', models.JSONField(default=list, help_text='Lista de puntos [[lat, lng], ...] sobre las calles')),
                ('tarifa', models.PositiveIntegerField(default=0)),
                ('tarifa_actualizada', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('representante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorridos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=60)),
                ('capacidad', models.PositiveSmallIntegerField(default=4)),
                ('aprobado', models.BooleanField(default=False, help_text='Lo revisa el representante antes de ser público')),
                ('conductores', models.ManyToManyField(blank=True, help_text='Conductores autorizados a manejar este vehículo', limit_choices_to={'perfil__rol': 'conductor'}, related_name='vehiculos_asignados', to=settings.AUTH_USER_MODEL)),
                ('recorrido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='transporte.recorrido')),
            ],
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('asientos_libres', models.PositiveSmallIntegerField(default=0)),
                ('actualizado', models.DateTimeField(blank=True, null=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas', to='transporte.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.PositiveSmallIntegerField()),
                ('categoria', models.CharField(choices=[('felicitacion', 'Felicitación'), ('sugerencia', 'Sugerencia'), ('reclamo', 'Reclamo')], max_length=15)),
                ('comentario', models.TextField(blank=True, max_length=500)),
                ('revisada', models.BooleanField(default=False)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='transporte.jornada')),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('jornada', 'pasajero')},
            },
        ),
        migrations.AddConstraint(
            model_name='jornada',
            constraint=models.UniqueConstraint(condition=models.Q(('fin__isnull', True)), fields=('conductor',), name='una_jornada_abierta_por_conductor'),
        ),
        migrations.AddConstraint(
            model_name='jornada',
            constraint=models.UniqueConstraint(condition=models.Q(('fin__isnull', True)), fields=('vehiculo',), name='una_jornada_abierta_por_vehiculo'),
        ),
    ]
